name = "spinogambino-bet-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-bet.com.es"
HMAC_KEY = "61d5b8f2d2a87ba38ee49fbd68c0efa579d625265679a4fb7645b3d2402a55ba"
COOKIE_NAME = "dp2"
PLAY_PATH = "explore"
BUTTON_ID = "pb222497ac858808ad37da77eeac2f915"
GATE_SALT = "17d3dc6280a4f3c8"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "zn8f"
CTA_SELECTOR = ".play-button"
